// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

if (!process.env["DATABASE_URL"]) {
  throw new Error("Database URL undefined");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
